dmoj/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import path, reverse
from django.utils.functional import lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import BlogPostSitemap, ContestSitemap, HomePageSitemap, OrganizationSitemap, ProblemSitemap, \
    SolutionSitemap, UrlSitemap, UserSitemap
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tasks, ticket, \
    two_factor, user, widgets
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, ProblemSelect2View, TicketUserSelect2View, \
    UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

register_patterns = [
    url(r'^activate/complete/$',
        TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                   title='Activation Successful!'),
        name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(title='Activation key invalid'),
        name='registration_activate'),
    url(r'^register/$',
        RegistrationView.as_view(title='Register'),
        name='registration_register'),
    url(r'^register/complete/$',
        TitledTemplateView.as_view(template_name='registration/registration_complete.html',
                                   title='Registration Completed'),
        name='registration_complete'),
    url(r'^register/closed/$',
        TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                   title='Registration not allowed'),
        name='registration_disallowed'),
    url(r'^login/$', user.CustomLoginView.as_view(), name='auth_login'),
    url(r'^logout/$', user.UserLogoutView.as_view(), name='auth_logout'),
    url(r'^password/change/$', user.CustomPasswordChangeView.as_view(), name='password_change'),
    url(r'^password/change/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    url(r'^password/reset/$', user.CustomPasswordResetView.as_view(
        template_name='registration/password_reset.html',
        html_email_template_name='registration/password_reset_email.html',
        email_template_name='registration/password_reset_email.txt',
    ), name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ), name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    url(r'^password/reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    url(r'^social/error/$', register.social_auth_error, name='social_auth_error'),

    url(r'^2fa/$', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    url(r'^2fa/enable/$', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    url(r'^2fa/refresh/$', two_factor.TOTPRefreshView.as_view(), name='refresh_2fa'),
    url(r'^2fa/disable/$', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    url(r'^2fa/webauthn/attest/$', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    url(r'^2fa/webauthn/assert/$', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    url(r'^2fa/webauthn/delete/(?P<pk>\d+)$', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),
    url(r'^2fa/scratchcode/generate/$', user.generate_scratch_codes, name='generate_scratch_codes'),

    url(r'api/token/generate/$', user.generate_api_token, name='generate_api_token'),
    url(r'api/token/remove/$', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        url(r'^$', view.as_view(), name=name),
        url(r'^(?P<page>\d+)$', view.as_view(), name=name),
    ])


urlpatterns = [
    url(r'^$', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    url(r'^500/$', exception),
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include(register_patterns)),
    url(r'^', include('social_django.urls')),

    url(r'^problems/$', problem.ProblemList.as_view(), name='problem_list'),
    url(r'^problems/random/$', problem.RandomProblem.as_view(), name='problem_random'),

    url(r'^problem/(?P<problem>[^/]+)', include([
        url(r'^$', problem.ProblemDetail.as_view(), name='problem_detail'),
        url(r'^/editorial$', problem.ProblemSolution.as_view(), name='problem_editorial'),
        url(r'^/raw$', problem.ProblemRaw.as_view(), name='problem_raw'),
        url(r'^/pdf$', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        url(r'^/pdf/(?P<language>[a-z-]+)$', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        url(r'^/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        url(r'^/submit$', problem.ProblemSubmit.as_view(), name='problem_submit'),
        url(r'^/resubmit/(?P<submission>\d+)$', problem.ProblemSubmit.as_view(), name='problem_submit'),

        url(r'^/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        url(r'^/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        url(r'^/submissions/(?P<user>[\w-]+)/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        url(r'^/$', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        url(r'^/test_data$', ProblemDataView.as_view(), name='problem_data'),
        url(r'^/test_data/init$', problem_init_view, name='problem_data_init'),
        url(r'^/test_data/diff$', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        url(r'^/data/(?P<path>.+)$', problem_data_file, name='problem_data_file'),

        url(r'^/tickets$', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        url(r'^/tickets/new$', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        url(r'^/manage/submission', include([
            url('^$', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            url('^/rejudge$', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            url('^/rejudge/preview$', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                name='problem_submissions_rejudge_preview'),
            url('^/rejudge/success/(?P<task_id>[A-Za-z0-9-]*)$', problem_manage.rejudge_success,
                name='problem_submissions_rejudge_success'),
            url('^/rescore/all$', problem_manage.RescoreAllSubmissionsView.as_view(),
                name='problem_submissions_rescore_all'),
            url('^/rescore/success/(?P<task_id>[A-Za-z0-9-]*)$', problem_manage.rescore_success,
                name='problem_submissions_rescore_success'),
        ])),
    ])),

    url(r'^submissions/', paged_list_view(submission.AllSubmissions, 'all_submissions')),
    url(r'^submissions/user/(?P<user>[\w-]+)/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions')),

    url(r'^src/(?P<submission>\d+)$', submission.SubmissionSource.as_view(), name='submission_source'),
    url(r'^src/(?P<submission>\d+)/raw$', submission.SubmissionSourceRaw.as_view(), name='submission_source_raw'),

    url(r'^submission/(?P<submission>\d+)', include([
        url(r'^$', submission.SubmissionStatus.as_view(), name='submission_status'),
        url(r'^/abort$', submission.abort_submission, name='submission_abort'),
    ])),

    url(r'^users/', include([
        url(r'^$', user.users, name='user_list'),
        url(r'^(?P<page>\d+)$', lambda request, page:
            HttpResponsePermanentRedirect('%s?page=%s' % (reverse('user_list'), page))),
        url(r'^find$', user.user_ranking_redirect, name='user_ranking_redirect'),
    ])),

    url(r'^user$', user.UserAboutPage.as_view(), name='user_page'),
    url(r'^edit/profile/$', user.edit_profile, name='user_edit_profile'),
    url(r'^data/prepare/$', user.UserPrepareData.as_view(), name='user_prepare_data'),
    url(r'^data/download/$', user.UserDownloadData.as_view(), name='user_download_data'),
    url(r'^user/(?P<user>[\w-]+)', include([

judge/models/ticket.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('ticket title'))
    user = models.ForeignKey(Profile, verbose_name=_('ticket creator'), related_name='tickets',
                             on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name=_('creation time'), auto_now_add=True)
    assignees = models.ManyToManyField(Profile, verbose_name=_('assignees'), related_name='assigned_tickets',
                                       blank=True)
    notes = models.TextField(verbose_name=_('quick notes'), blank=True,
                             help_text=_('Staff notes for this issue to aid in processing.'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('linked item type'),
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(verbose_name=_('linked item ID'))
    linked_item = GenericForeignKey()
    is_open = models.BooleanField(verbose_name=_('is ticket open?'), default=True)


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_('ticket'), related_name='messages',
                               related_query_name='message', on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, verbose_name=_('poster'), related_name='ticket_messages',
                             on_delete=models.CASCADE)
    body = models.TextField(verbose_name=_('message body'))
    time = models.DateTimeField(verbose_name=_('message time'), auto_now_add=True)

judge/views/preview.py
from django.http import HttpResponseBadRequest
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MarkdownPreviewView(TemplateResponseMixin, ContextMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            self.preview_data = data = request.POST['content']
        except KeyError:
            return HttpResponseBadRequest('No preview data specified.')

        return self.render_to_response(self.get_context_data(
            preview_data=data,
        ))


class ProblemMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'problem/preview.html'


class BlogMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'blog/preview.html'


class ContestMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'contest/preview.html'


class CommentMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'comments/preview.html'


class FlatPageMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'flatpage-preview.html'


class ProfileMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'user/preview.html'


class OrganizationMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'organization/preview.html'


class SolutionMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'solution-preview.html'


class LicenseMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'license-preview.html'


class TicketMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'ticket/preview.html'


class DefaultMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'default-preview.html'

templates/ticket/edit-notes.html
<form id="edit-notes" action="{{ url('ticket_notes', ticket.id) }}" method="post">
    {% csrf_token %}
    {{ form.notes }}
    <button type="submit" class="submit">{{ _('Update') }}</button>
</form>

templates/ticket/message.html
<section id="message-{{ message.id }}" class="message">
    <div class="info">
        <a href="{{ url('user_page', message.user.user.username) }}" class="user">
            <img src="{{ gravatar(message.user, 135) }}" class="gravatar">
            <div class="username {{ message.user.css_class }}">{{ message.user.user.username }}</div>
        </a>
    </div>
    <div class="detail">
        <div class="header">
            <div class="relative-time"></div>
            <div class="message-date">{{ message.time|date('DATE_FORMAT') }}</div>
            <div class="message-time">{{ message.time|time('TIME_FORMAT') }}</div>
        </div>
        <div class="content content-description">
            {{ message.body|markdown('ticket', MATH_ENGINE)|reference|str|safe }}
        </div>
    </div>
</section>

templates/ticket/new.html
{% extends "base.html" %}

{% block media %}
    {{ form.media.css }}
    <style>
        form#ticket-form {
            display: block;
            margin: 0 auto;
            width: 100%;
            max-width: 750px;
            padding-top: 1em;
        }

        #id_title {
            width: 100%;
        }

        form#ticket-form .submit {
            margin: 10px 0 0 auto;
        }
    </style>
{% endblock %}

{% block js_media %}{{ form.media.js }}{% endblock %}

{% block body %}
    <form id="ticket-form" action="" method="POST" class="form-area">
        {% block guideline_message %}{% endblock %}
        {% csrf_token %}
        <div class="title-block{% if form.title.errors %} error{% endif %}">{{ form.title }}</div>
        {% if form.errors %}
            <div class="form-errors">
                {{ form.non_field_errors() }}
                {{ form.title.errors }}
                {{ form.body.errors }}
            </div>
        {% endif %}
        <div class="body-block">{{ form.body }}</div>
        <button type="submit" class="submit">{{ _('Create') }}</button>
    </form>
{% endblock %}

templates/ticket/new_problem.html
{% extends "ticket/new.html" %}

{% block guideline_message %}
    {% if not request.in_contest %}
        <div class="alert alert-warning alert-dismissable">
            <a class="close">x</a>
            <b>{{ _('Thanks for opening a ticket!') }}</b>
            <br><br>
            {{ _('Please keep in mind that this form is for reporting issues with a problem statement, and not for asking for help. If you require assistance on solving a problem, ask in the comments instead.') }}
        </div>
    {% endif %}
{% endblock %}

templates/ticket/preview.html
{{ preview_data|markdown('ticket', MATH_ENGINE)|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/ticket/row.html
<tr id="ticket-{{ ticket.id }}">
    <td><i class="fa {% if ticket.is_open %}fa-exclamation-circle{% else %}fa-check-circle-o{% endif %}"></i></td>
    <td>{{ ticket.id }}</td>
    <td><a href="{{ url('ticket', ticket.id) }}">{{ ticket.title }}</a></td>
    <td>{{ link_user(ticket.user) }}</td>
    <td>{{ link_users(ticket.assignees.all()) }}</td>
</tr>

templates/ticket/ticket.html
{% extends "base.html" %}
{% block media %}
    {{ form.media.css }}
    <style>
        #content > h2:first-child small {
            color: #999;
            font-size: 0.9em;
            margin-left: 0.3em;
        }

        #content > h2:first-child .status, #content > h2:first-child .title {
            display: inline;
        }

        #content > h2:first-child .fa-check-circle-o {
            color: #00a900;
        }

        #content > h2:first-child .fa-exclamation-circle {
            color: darkred;
        }

        .container {
            width: 100%;
            margin: 0 auto;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap-reverse;
            max-width: 1000px;
        }

        .ticket-sidebar {
            flex: 1;
            padding: 10px 0 0 10px;
            min-width: 150px;
            max-width: 200px;
        }

        .ticket-info {
            position: sticky;
            top: 60px;
        }

        .ticket-messages {
            flex: 1;
        }

        .info-box {
            margin: 5px 0 10px;
            border: 1px #999 solid;
            border-radius: 5px;
        }

        .info-title {
            padding: 2px 5px;
            font-weight: 600;
            border-bottom: 1px #999 solid;
            background: #eee;
            border-radius: 5px 5px 0 0;
        }

        .info-data {
            padding: 2px 5px;
        }

        .info-empty {
            color: #999;
            font-style: italic;
        }

        .close-ticket {
            display: block;
            width: 100%;
            background: linear-gradient(to bottom, #4bad00 0%, #278811 100%);
            border-color: #24710e;
            font-weight: 600;
        }

        .close-ticket:hover {
            background: #24710e;
        }

        .open-ticket {
            display: block;
            width: 100%;
            background: linear-gradient(to bottom, #ff130f, #b03d17);
            border-color: #853011;
            font-weight: 600;
        }

        .open-ticket:hover {
            background: #853011;
        }

        a.edit-notes {
            float: right;
        }

        #ticket-notes .info-real :first-child {
            margin-top: 0;
        }

        #ticket-notes .info-real :last-child {
            margin-bottom: 0;
        }

        .message {
            display: flex;
            padding-top: 15px;
        }

        .message .info {
            width: 130px;
        }

        .message .username {
            text-align: center;
        }

        .message .gravatar {
            width: 80px;
            display: block;
            margin: 0 auto;
        }

        .message .message-date, .message .message-time {
            display: inline-block;
        }

        .message .detail {
            border: 1px #999 solid;
            border-radius: 5px;
            flex: 1;
            min-width: 200px;
        }

        .message .header {
            background: #eee;
            color: #777;
            border-bottom: 1px solid #999;
            border-radius: 5px 5px 0 0;
            padding: 2px 7px;
            text-align: right;
        }

        .message .content {
            padding: 7px;
        }

        .message .content :first-child {
            margin-top: 0;
        }

        .message .content :last-child {
            margin-bottom: 0;
        }

        .new-message .detail {
            padding: 8px 10px;
        }

        .new-message .submit, #edit-notes .submit {
            margin: 10px 0 0 auto;
        }
    </style>
{% endblock %}

{% block js_media %}
    {{ form.media.js }}
    <script src="{{ static('libs/featherlight/featherlight.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ static('event.js') }}"></script>
    <script type="text/javascript">
        $(function () {
            var $h2 = $('#content').find('> h2:first-child');
            var $status = $h2.find('.status i'), $title = $h2.find('.title');

            function update_ticket_state(open) {
                if (open)
                    $status.removeClass('fa-check-circle-o').addClass('fa-exclamation-circle');
                else
                    $status.removeClass('fa-exclamation-circle').addClass('fa-check-circle-o');
                $('.close-ticket').toggle(open);
                $('.open-ticket').toggle(!open);
            }

            $('.close-ticket, .open-ticket').click(function () {
                var open = $(this).attr('data-open') == '1';
                $.ajax({
                    url: $(this).attr('data-ajax'), type: 'POST',
                    success: function () {
                        update_ticket_state(open);
                    },
                    error: function (data) {
                        alert('Could not change ticket: ' + data.responseText);
                    }
                });
            });

            $('.edit-notes').featherlight({
                afterOpen: function () {
                    var $form = $('#edit-notes');
                    $form.find('.submit').click(function () {
                        $.post($form.attr('action'), $form.serialize()).done(function (data) {
                            $('#ticket-notes').find('.info-empty').toggle(!data).end().find('.info-real').html(data);
                            $.featherlight.current().close();
                        });
                        return false;
                    });
                }
            });

            var page_ref_key = 'ticket:open:{{ ticket.id }}', page_close_key = page_ref_key + ':close';
            var page_ref;

            function increase_page_ref() {
                if (page_ref_key in localStorage)
                    localStorage[page_ref_key] = page_ref = +localStorage[page_ref_key] + 1;
                else
                    localStorage[page_ref_key] = page_ref = 1;
            }

            function decrease_page_ref() {
                if (page_ref_key in localStorage) {
                    localStorage[page_close_key] = page_ref;
                    delete localStorage[page_close_key];
                    localStorage[page_ref_key] = +localStorage[page_ref_key] - 1;
                }
                page_ref = null;
            }

            function is_highest_ref() {
                console.log(localStorage[page_ref_key], page_ref);
                if (page_ref_key in localStorage)
                    return +localStorage[page_ref_key] == page_ref;
                return true;
            }

            $(window).on('storage', function (e) {
                e = e.originalEvent;
                if (e.key == page_close_key && e.newValue !== null)
                    if (page_ref != null && page_ref > +e.newValue)
                        --page_ref;
            });

            register_notify('ticket', {
                change: function (enabled) {
                    if (enabled)
                        increase_page_ref();
                }
            });

            $(window).on('beforeunload', function () {
                decrease_page_ref();
            });

            function ticket_status(ticket) {
                update_ticket_state(ticket.open);
                if (is_highest_ref())
                    notify('ticket', (ticket.open ? '{{ _('Reopened: ') }}' :
                        '{{ _('Closed: ') }}') + $title.text());
            }

            function ticket_message(ticket) {
                console.log('Fetching data for: ' + ticket.message);
                $.ajax({
                    url: '{{ url('ticket_message_ajax', ticket.id) }}',
                    data: {message: ticket.message},
                    success: function (data) {
                        console.log('Got data for: ' + ticket.message);
                        console.log(data);
                        $('#messages').append($(data.message));
                    },
                    error: function (data) {
                        if (data.status === 403)
                            console.log('No right to see: ' + ticket.message);
                        else {
                            console.log('Could not load ticket message:');
                            console.log(data.responseText);
                        }
                    }
                });
            }

            window.load_dynamic_update = function (last_msg) {
                return new EventReceiver(
                    "{{ EVENT_DAEMON_LOCATION }}", "{{ EVENT_DAEMON_POLL_LOCATION }}",
                    ['ticket-{{ ticket.id }}'], last_msg, function (message) {
                        console.log(message);
                        switch (message.type) {
                            case 'ticket-status':
                                ticket_status(message);
                                break;
                            case 'ticket-message':
                                ticket_message(message);
                                break;
                        }
                    }
                );
            }
        });
    </script>

    {% if last_msg %}
        <script type="text/javascript">
            $(function () {
                load_dynamic_update({{last_msg}});
            });
        </script>
    {% endif %}
{% endblock %}

{% block content_title %}
    <div class="status">
        <i class="fa {% if ticket.is_open %}fa-exclamation-circle{% else %}fa-check-circle-o{% endif %}"></i>
    </div>
    <div class="title">{{ ticket.title }}</div><small>#{{ ticket.id }}</small>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="ticket-messages">
            <main id="messages">
                {% for message in ticket_messages %}
                    {% include "ticket/message.html" %}
                {% endfor %}
            </main>
            <hr>
            <section class="message new-message">
                <div class="info">
                    <a href="{{ url('user_page', request.user.username) }}" class="user">
                        <img src="{{ gravatar(request.user, 135) }}" class="gravatar">
                        <div class="username {{ request.profile.css_class }}">{{ request.user.username }}</div>
                    </a>
                </div>
                <div class="detail">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if form.non_field_errors() or form.body.errors %}
                            <div class="form-errors">
                                {{ form.non_field_errors() }}
                                {{ form.body.errors }}
                            </div>
                        {% endif %}
                        <div class="body-block">{{ form.body }}</div>
                        <button type="submit" class="submit">{{ _('Post') }}</button>
                    </form>
                </div>
            </section>
        </div>
        <aside class="ticket-sidebar">
            <div class="ticket-info">
                <div class="info-box">
                    <div class="info-title">{{ _('Associated object') }}</div>
                    <div class="info-data">
                        <a href="{{ ticket.linked_item.get_absolute_url() }}">{{ ticket.linked_item }}</a>
                    </div>
                </div>
                <div class="info-box">
                    <div class="info-title">
                        {% trans trimmed count=assignees|length %}
                            Assignee
                        {% pluralize %}
                            Assignees
                        {% endtrans %}
                    </div>
                    <div class="info-data">
                        {% if assignees %}
                            {{ link_users(assignees) }}
                        {% else %}
                            <div class="info-empty">{{ _('No one is assigned.') }}</div>
                        {% endif %}
                    </div>
                </div>

                <button data-ajax="{{ url('ticket_close', ticket.id) }}" data-open="0" class="close-ticket"
                        {% if not ticket.is_open %}style="display: none"{% endif %}>{{ _('Close ticket') }}</button>
                <button data-ajax="{{ url('ticket_open', ticket.id) }}" data-open="1" class="open-ticket"
                        {% if ticket.is_open %}style="display: none"{% endif %}>{{ _('Reopen ticket') }}</button>

                {% if perms.judge.change_ticket or request.profile in assignees %}
                    <div class="info-box">
                        <div class="info-title">{{ _('Assignee notes') }}
                            <a href="#" data-featherlight="{{ url('ticket_notes', ticket.id) }}" class="edit-notes">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </div>
                        <div id="ticket-notes" class="info-data">
                            <div{% if ticket.notes %} style="display: none"{% endif %} class="info-empty">
                                {{ _('Nothing here.') }}
                            </div>
                            <div class="info-real">{{ ticket.notes|linebreaks }}</div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </aside>
    </div>
{% endblock %}