dmoj/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import path, reverse
from django.utils.functional import lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import BlogPostSitemap, ContestSitemap, HomePageSitemap, OrganizationSitemap, ProblemSitemap, \
    SolutionSitemap, UrlSitemap, UserSitemap
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tasks, ticket, \
    two_factor, user, widgets
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, ProblemSelect2View, TicketUserSelect2View, \
    UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

register_patterns = [
    url(r'^activate/complete/$',
        TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                   title='Activation Successful!'),
        name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    url(r'^activate/(?P<activation_key>\w+)/$',
        ActivationView.as_view(title='Activation key invalid'),
        name='registration_activate'),
    url(r'^register/$',
        RegistrationView.as_view(title='Register'),
        name='registration_register'),
    url(r'^register/complete/$',
        TitledTemplateView.as_view(template_name='registration/registration_complete.html',
                                   title='Registration Completed'),
        name='registration_complete'),
    url(r'^register/closed/$',
        TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                   title='Registration not allowed'),
        name='registration_disallowed'),
    url(r'^login/$', user.CustomLoginView.as_view(), name='auth_login'),
    url(r'^logout/$', user.UserLogoutView.as_view(), name='auth_logout'),
    url(r'^password/change/$', user.CustomPasswordChangeView.as_view(), name='password_change'),
    url(r'^password/change/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    url(r'^password/reset/$', user.CustomPasswordResetView.as_view(
        template_name='registration/password_reset.html',
        html_email_template_name='registration/password_reset_email.html',
        email_template_name='registration/password_reset_email.txt',
    ), name='password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ), name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    url(r'^password/reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    url(r'^social/error/$', register.social_auth_error, name='social_auth_error'),

    url(r'^2fa/$', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    url(r'^2fa/enable/$', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    url(r'^2fa/refresh/$', two_factor.TOTPRefreshView.as_view(), name='refresh_2fa'),
    url(r'^2fa/disable/$', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    url(r'^2fa/webauthn/attest/$', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    url(r'^2fa/webauthn/assert/$', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    url(r'^2fa/webauthn/delete/(?P<pk>\d+)$', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),
    url(r'^2fa/scratchcode/generate/$', user.generate_scratch_codes, name='generate_scratch_codes'),

    url(r'api/token/generate/$', user.generate_api_token, name='generate_api_token'),
    url(r'api/token/remove/$', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        url(r'^$', view.as_view(), name=name),
        url(r'^(?P<page>\d+)$', view.as_view(), name=name),
    ])


urlpatterns = [
    url(r'^$', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    url(r'^500/$', exception),
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include(register_patterns)),
    url(r'^', include('social_django.urls')),

    url(r'^problems/$', problem.ProblemList.as_view(), name='problem_list'),
    url(r'^problems/random/$', problem.RandomProblem.as_view(), name='problem_random'),

    url(r'^problem/(?P<problem>[^/]+)', include([
        url(r'^$', problem.ProblemDetail.as_view(), name='problem_detail'),
        url(r'^/editorial$', problem.ProblemSolution.as_view(), name='problem_editorial'),
        url(r'^/raw$', problem.ProblemRaw.as_view(), name='problem_raw'),
        url(r'^/pdf$', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        url(r'^/pdf/(?P<language>[a-z-]+)$', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        url(r'^/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        url(r'^/submit$', problem.ProblemSubmit.as_view(), name='problem_submit'),
        url(r'^/resubmit/(?P<submission>\d+)$', problem.ProblemSubmit.as_view(), name='problem_submit'),

        url(r'^/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        url(r'^/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        url(r'^/submissions/(?P<user>[\w-]+)/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        url(r'^/$', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        url(r'^/test_data$', ProblemDataView.as_view(), name='problem_data'),
        url(r'^/test_data/init$', problem_init_view, name='problem_data_init'),
        url(r'^/test_data/diff$', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        url(r'^/data/(?P<path>.+)$', problem_data_file, name='problem_data_file'),

        url(r'^/tickets$', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        url(r'^/tickets/new$', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        url(r'^/manage/submission', include([
            url('^$', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            url('^/rejudge$', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            url('^/rejudge/preview$', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                name='problem_submissions_rejudge_preview'),
            url('^/rejudge/success/(?P<task_id>[A-Za-z0-9-]*)$', problem_manage.rejudge_success,
                name='problem_submissions_rejudge_success'),
            url('^/rescore/all$', problem_manage.RescoreAllSubmissionsView.as_view(),
                name='problem_submissions_rescore_all'),
            url('^/rescore/success/(?P<task_id>[A-Za-z0-9-]*)$', problem_manage.rescore_success,
                name='problem_submissions_rescore_success'),
        ])),
    ])),

    url(r'^submissions/', paged_list_view(submission.AllSubmissions, 'all_submissions')),
    url(r'^submissions/user/(?P<user>[\w-]+)/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions')),

    url(r'^src/(?P<submission>\d+)$', submission.SubmissionSource.as_view(), name='submission_source'),
    url(r'^src/(?P<submission>\d+)/raw$', submission.SubmissionSourceRaw.as_view(), name='submission_source_raw'),

    url(r'^submission/(?P<submission>\d+)', include([
        url(r'^$', submission.SubmissionStatus.as_view(), name='submission_status'),
        url(r'^/abort$', submission.abort_submission, name='submission_abort'),
    ])),

    url(r'^users/', include([
        url(r'^$', user.users, name='user_list'),
        url(r'^(?P<page>\d+)$', lambda request, page:
            HttpResponsePermanentRedirect('%s?page=%s' % (reverse('user_list'), page))),
        url(r'^find$', user.user_ranking_redirect, name='user_ranking_redirect'),
    ])),

    url(r'^user$', user.UserAboutPage.as_view(), name='user_page'),
    url(r'^edit/profile/$', user.edit_profile, name='user_edit_profile'),
    url(r'^data/prepare/$', user.UserPrepareData.as_view(), name='user_prepare_data'),
    url(r'^data/download/$', user.UserDownloadData.as_view(), name='user_download_data'),
    url(r'^user/(?P<user>[\w-]+)', include([

judge/models/ticket.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('ticket title'))
    user = models.ForeignKey(Profile, verbose_name=_('ticket creator'), related_name='tickets',
                             on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name=_('creation time'), auto_now_add=True)
    assignees = models.ManyToManyField(Profile, verbose_name=_('assignees'), related_name='assigned_tickets',
                                       blank=True)
    notes = models.TextField(verbose_name=_('quick notes'), blank=True,
                             help_text=_('Staff notes for this issue to aid in processing.'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('linked item type'),
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(verbose_name=_('linked item ID'))
    linked_item = GenericForeignKey()
    is_open = models.BooleanField(verbose_name=_('is ticket open?'), default=True)


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_('ticket'), related_name='messages',
                               related_query_name='message', on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, verbose_name=_('poster'), related_name='ticket_messages',
                             on_delete=models.CASCADE)
    body = models.TextField(verbose_name=_('message body'))
    time = models.DateTimeField(verbose_name=_('message time'), auto_now_add=True)

judge/views/preview.py
from django.http import HttpResponseBadRequest
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MarkdownPreviewView(TemplateResponseMixin, ContextMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            self.preview_data = data = request.POST['content']
        except KeyError:
            return HttpResponseBadRequest('No preview data specified.')

        return self.render_to_response(self.get_context_data(
            preview_data=data,
        ))


class ProblemMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'problem/preview.html'


class BlogMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'blog/preview.html'


class ContestMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'contest/preview.html'


class CommentMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'comments/preview.html'


class FlatPageMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'flatpage-preview.html'


class ProfileMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'user/preview.html'


class OrganizationMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'organization/preview.html'


class SolutionMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'solution-preview.html'


class LicenseMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'license-preview.html'


class TicketMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'ticket/preview.html'


class DefaultMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'default-preview.html'

templates/comments/content.html
{{ comment.body|markdown('comment', MATH_ENGINE)|reference|str|safe }}

templates/comments/edit-ajax.html
<div class="comment-submit">
    <form id="comment-edit" action="{{ request.get_full_path() }}" method="post">
        <span style="display: none" class="comment-id">{{ comment.id }}</span>
        <span style="display: none" class="read-back">{{ url('comment_content', comment.id) }}</span>
        {% csrf_token %}
        {% if form.non_field_errors() or form.body.errors %}
            <div class="form-errors">
                {{ form.non_field_errors() }}
                {{ form.body.errors }}
            </div>
        {% endif %}
        <div class="comment-post-wrapper">
            <div id="comment-form-body">{{ form.body }}</div>
        </div>
        <hr>
        <input style="float: right" type="submit" value="Post!" class="button">
    </form>
</div>

templates/comments/edit.html
{% extends "base.html" %}
{% block media %}
    {% compress css %}
        {{ form.media.css }}
    {% endcompress %}
{% endblock %}

{% block js_media %}
    {{ form.media.js }}
{% endblock %}
{% block body %}
    <div class="form-area">{% include "comments/edit-ajax.html" %}</div>
{% endblock %}

templates/comments/math.html
{% compress js, inline %}
    <script src="{{ static('pagedown_math.js') }}"></script>
{% endcompress %}

templates/comments/media-css.html
{% compress css %}
    {{ comment_form.media.css }}
    <style media="all">
        .featherlight {
            z-index: 1000;
        }

        .revision-text p:first-child {
            margin-top: 0;
        }

        .revision-text p:last-child {
            margin-bottom: 0;
        }

        .featherlight-edit .featherlight-content {
            background: #FAFAFA;
            padding: 10px 15px 10px 10px;
            border-radius: 10px;
            border: 1px solid #CCC;
        }

        .new-comments .comment-display {
            display: flex;
            margin-top: -0.25em !important;
            padding-left: 1em;
            padding-top: 0.5em !important;
            border: 1px solid #ccc;
            background: #fafafa;
        }

        .new-comments .comment .detail {
            margin: 0px 15px 0px;
            width: 100%;
        }

        .new-comments .comment-edits {
            padding-right: 0.75em;
        }

        .new-comments .comment .detail .header {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            padding: 2px 0px;
            font-weight: normal;
            border-bottom: 1px #888 solid;
            color: #888;
            text-align: right;
        }

        .previous-revision, .next-revision {
            color: #444;
        }

        .new-comments .header i {
            color: #888 !important;
        }

        .new-comments .info {
            padding-top: 0.4em;
            display: flex;
        }

        .new-comments .gravatar {
            width: 75px;
            max-width: 75px;
        }

        .new-comments .gravatar-mobile {
            display: none;
        }

        .new-comments .gravatar-main {
            display: unset;
        }

        .new-comments .vote {
            margin-right: 1em;
            height: 75px;
            padding-top: 0.4em;
        }

        @media (max-width: 760px) {
            .new-comments .gravatar {
                width: 10px;
                max-width: 10px;
            }

            .new-comments .gravatar-mobile {
                display: unset;
            }

            .new-comments .gravatar-main {
                display: none;
            }

            .new-comments .vote {
                margin-right: 0em;
            }
        }

        .new-comments .comment-display {
            border-radius: 4px;
        }

        .new-comments .comment:target > .comment-display {
            border: 1px solid #2980b9;
            border-left: 10px solid #2980b9;
            padding-left: 5px;
        }

        .comments.top-level-comments {
            margin-bottom: -3px;
        }

        .bad-comment {
            opacity: 0.3;
        }

        .bad-comment:hover {
            opacity: 1;
            /* This is necessary to prevent random flickering */
            -webkit-transform: translatez(0);
            -moz-transform: translatez(0);
            -ms-transform: translatez(0);
            -o-transform: translatez(0);
            transform: translatez(0);
        }
    </style>
{% endcompress %}

templates/comments/media-js.html
<script src="{{ static('libs/featherlight/featherlight.min.js') }}" type="text/javascript"></script>
{% compress js %}
    {{ comment_form.media.js }}
    {% if not REQUIRE_JAX %}
        <script type="text/javascript">
            $(function () {
                $('#id_body').keypress(function () {
                    if (!("MathJax" in window)) {
                        $.ajax({
                            type: "GET",
                            url: '{{ static('mathjax_config.js') }}',
                            dataType: "script",
                            cache: true,
                            success: function () {
                                $.ajax({
                                    type: "GET",
                                    url: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config=TeX-AMS_HTML',
                                    dataType: "script",
                                    cache: true,
                                    success: function () {
                                        mathjax_pagedown($);
                                    }
                                });
                            }
                        });
                    }
                });
            });
        </script>
    {% endif %}
    <script type="text/javascript">
        $(document).ready(function () {
            window.reply_comment = function (parent) {
                var $comment_reply = $('#comment-' + parent + '-reply');
                var reply_id = 'reply-' + parent;
                if ($comment_reply.find('#' + reply_id).length == 0) {
                    var $reply_form = $('#new-comment').clone(true).prop('id', reply_id);
                    $reply_form.find('h3').html('{{ _('Replying to comment') }}');
                    $reply_form.prepend('<a class="close">x</a>');
                    $reply_form.find('form.comment-submit-form input#id_parent').val(parent);
                    $reply_form.appendTo($comment_reply);
                    register_dmmd_preview($('#' + reply_id + ' #id_body-preview'));
                }
                $comment_reply.fadeIn();

                $('html, body').animate({
                    scrollTop: $comment_reply.offset().top - $('#navigation').height() - 4
                }, 500);
            };

            $(document).on('click', '.close', function() {
                $(this).closest('.reply-comment').fadeOut();
            });

            function update_math($comment) {
                if ('MathJax' in window) {
                    var $body = $comment.find('.comment-body');
                    MathJax.Hub.Queue(['Typeset', MathJax.Hub, $body[0]], function () {
                        $body.find('.tex-image').hide();
                        $body.find('.tex-text').show();
                    });
                }
            }

            window.show_revision = function (comment_id, offset) {
                var $comment = $("#comment-" + comment_id);

                // If .comment-body is hidden, then this is a bad comment that the user has not clicked
                // Thus the revision retrieval should do nothing
                if (!$comment.find('.comment-body').is(':visible'))
                    return;

                var cur_revision = parseInt($comment.attr("data-revision"));
                var max_revision = parseInt($comment.attr("data-max-revision"));
                var revision_ajax = $comment.attr("data-revision-ajax");
                var show_revision = cur_revision + offset;

                // Do nothing if desired revision is out of buonds
                if (show_revision < 0 || show_revision > max_revision)
                    return;

                $comment.attr("data-revision", show_revision);

                $.get(revision_ajax, {
                    revision: show_revision
                }).done(function (body) {
                    $comment.find('.previous-revision').css({visibility: show_revision == 0 ? 'hidden' : ''});
                    $comment.find('.next-revision').css({visibility: show_revision == max_revision ? 'hidden' : ''});
                    var $content = $comment.find('.content').html(body);

                    var edit_text = '{{ _('edit {edits}') }}'.replace("{edits}", show_revision);

                    if (show_revision == 0) {
                        edit_text = '{{ _('original') }}';
                    } else if (show_revision == max_revision && max_revision == 1) {
                        edit_text = '{{ _('edited') }}';
                    }

                    $comment.find('.comment-edit-text').text(' ' + edit_text + ' ');
                    update_math($content);
                    if (window.add_code_copy_buttons)
                        window.add_code_copy_buttons($content);
                });
            };

            function ajax_vote(url, id, delta, on_success) {
                return $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        id: id
                    },
                    success: function (data, textStatus, jqXHR) {
                        var score = $('#comment-' + id + ' .comment-score').first();
                        score.text(parseInt(score.text()) + delta);
                        if (typeof on_success !== 'undefined')
                            on_success();
                    },
                    error: function (data, textStatus, jqXHR) {
                        alert('Could not vote: ' + data.responseText);
                    }
                });
            }

            var get_$votes = function (id) {
                var $comment = $('#comment-' + id);
                return {
                    upvote: $comment.find('.upvote-link').first(),
                    downvote: $comment.find('.downvote-link').first()
                };
            };

            window.comment_upvote = function (id) {
                ajax_vote('{{ url('comment_upvote') }}', id, 1, function () {
                    var $votes = get_$votes(id);
                    if ($votes.downvote.hasClass('voted'))
                        $votes.downvote.removeClass('voted');
                    else
                        $votes.upvote.addClass('voted');
                });
            };

            window.comment_downvote = function (id) {
                ajax_vote('{{ url('comment_downvote') }}', id, -1, function () {
                    var $votes = get_$votes(id);
                    if ($votes.upvote.hasClass('voted'))
                        $votes.upvote.removeClass('voted');
                    else
                        $votes.downvote.addClass('voted');
                });
            };

            var $comments = $('.comments');
            $comments.find('a.hide-comment').click(function (e) {
                e.preventDefault();
                if (!(e.ctrlKey || e.metaKey || confirm('Are you sure you want to hide this comment?')))
                    return;

                var id = $(this).attr('data-id');
                $.post('{{ url('comment_hide') }}', {id: id}).then(function () {
                    $('#comment-' + id).remove();
                    $('#comment-' + id + '-children').remove();
                }).catch(function () {
                    alert('Failed.');
                });
            });

            $comments.find('a.edit-link').featherlight({
                afterOpen: function () {
                    if ('DjangoPagedown' in window) {
                        var $wmd = $('.featherlight .wmd-input');
                        if ($wmd.length) {
                            window.DjangoPagedown.createEditor($wmd.get(0));
                            if ('MathJax' in window) {
                                var preview = $('.featherlight div.wmd-preview')[0];
                                window.editors[$wmd.attr('id')].hooks.chain('onPreviewRefresh', function () {
                                    MathJax.Hub.Queue(['Typeset', MathJax.Hub, preview]);
                                });
                                MathJax.Hub.Queue(['Typeset', MathJax.Hub, preview]);
                            }
                        }
                    }
                    $('#comment-edit').submit(function (event) {
                        event.preventDefault();
                        var id = $('#comment-edit').find('.comment-id').text();
                        var readback = $('#comment-edit').find('.read-back').text();
                        $.post($(this).attr('action'), $(this).serialize()).done(function (data) {
                            $.featherlight.current().close();
                            $.ajax({
                                url: readback
                            }).done(function (data) {
                                var $comment = $('#comment-' + id);
                                var $area = $comment.find('.comment-body').first();
                                $area.html(data);
                                update_math($comment);
                                if (window.add_code_copy_buttons)
                                    window.add_code_copy_buttons($area);
                                var $edits = $comment.find('.comment-edits').first();
                                $edits.text('updated');
                            }).fail(function () {
                                console.log('Failed to update comment:' + id);
                            });
                        });
                    });
                },
                variant: 'featherlight-edit'
            });

            $('votes-link').find('a[data-featherlight]').featherlight();

            var $root = $('html, body');
            $comments.find('a.comment-link').click(function () {
                var href = $.attr(this, 'href');
                $root.animate({
                    scrollTop: $(href).offset().top
                }, 500, function () {
                    window.location.hash = href;
                });
                return false;
            });

            $('img.unveil').unveil(200);

            window.comment_show_content = function (comment_id) {
                var $comment = $('#comment-' + comment_id);
                $comment.find('.comment-body').show();
                $comment.find('.bad-comment-body').hide();
            };
        });
    </script>
{% endcompress %}

templates/comments/preview.html
{{ preview_data|markdown('comment', MATH_ENGINE)|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/comments/revision-ajax.html
{% with node=revision.field_dict %}
    <div class="comment-body">{{ node.body|markdown('comment', MATH_ENGINE)|reference|str|safe }}</div>
{% endwith %}

templates/comments/votes.html
<h2 style="text-align: center">{{ _('Votes') }}</h2>
<table class="table" style="display: table">
    <thead>
    <tr>
        <th>{{ _('Voter') }}</th>
        <th>{{ _('Score') }}</th>
    </tr>
    </thead>
    <tbody>
    {% for vote in votes %}
        <tr>
            <td>{{ link_user(vote.voter) }}</td>
            <td>{{ vote.score }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="2">{{ _('No votes') }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>